### PR TITLE
fix for skill strength not appearing after practice

### PR DESCRIPTION
**Pull request by AbsolutelyFreeWeb**
The ajax trigger was not working. This is tested working in latest Chrome. 
Not tested with Mozilla. Let me know if I need to put back the ajax complete trigger as well.

### CODE REVIEW

**Comment by halfdan** [comment]
@AbsolutelyFreeWeb Thanks for this. Can you remove the commented console.debugs in there?

**Comment by AbsolutelyFreeWeb** [comment]
@halfdan You're welcome. Thank you! I use your script every day ^^  console.debugs are removed.

**Comment by AbsolutelyFreeWeb** [comment]
@halfdan Did you need anything else to add it ?

**Comment by halfdan** [comment]
Nope - simply forgot to merge. Thanks for the nudge:)

**Pull request merged**
